language: php

os: linux

dist: focal

php:
- 7.4

services:
- mysql

addons:
  chrome: stable

install:
- cp .env.testing .env
- mysql -e 'create database justeat;'
- composer install --no-interaction --prefer-dist --no-suggest
- php artisan key:generate
- php artisan migrate:fresh
- php artisan dusk:chrome-driver

before_script:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - php artisan serve &

script:
    - php artisan test
    - php artisan dusk

branches:
  only:
    - main
    - develop

notifications:
    slack: ub-es-2020-justeat:tStsxAy5WWl74qZJWBxGJYAi
    recipients:
        - xavidejuan@gmail.com
    on_success: always
    on_failure: always
