language: php

os: linux

dist: focal

php:
- 7.4

services:
- mysql

addons:
  chrome: stable

install:
- cp .env.testing .env
- mysql -e 'create database justeat_test;'
- travis_retry composer install --no-interaction --prefer-dist --no-suggest
- php artisan key:generate
- php artisan migrate:fresh
- php artisan dusk:chrome-driver
- travis_retry npm install
- npm run prod

before_script:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - php artisan serve -q &

script:
    - vendor/bin/phpunit --coverage-clover ./build/logs/clover.xml
    - php artisan dusk --coverage-clover ./build/logs/clover-dusk.xml

after_script:
- vendor/bin/php-coveralls -v

branches:
  only:
    - main
    - develop

notifications:
    slack: ub-es-2020-justeat:tStsxAy5WWl74qZJWBxGJYAi
    recipients:
        - xavidejuan@gmail.com
    on_success: always
    on_failure: always
