deploy.staging.justeat.xavidejuan.com:
  hostname: deploy.staging.justeat.xavidejuan.com
  user: deploy
  port: 22
  configFile: ~/.ssh/config
  identityFile: ~/.ssh/deploy_justeat
  forwardAgent: true
  multiplexing: true
  sshOptions:
    UserKnownHostsFile: /dev/null
    StrictHostKeyChecking: no
  stage: staging
  branch: staging
  deploy_path: /var/www/vhosts/justeat/staging

deploy.justeat.xavidejuan.com:
  hostname: deploy.justeat.xavidejuan.com
  user: deploy
  port: 22
  configFile: ~/.ssh/config
  identityFile: ~/.ssh/deploy_justeat
  forwardAgent: true
  multiplexing: true
  sshOptions:
    UserKnownHostsFile: /dev/null
    StrictHostKeyChecking: no
  stage: production
  branch: master
  deploy_path: /var/www/vhosts/justeat/production
